# Generated by Django 4.2 on 2023-07-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCartPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PTTBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
