# Generated by Django 4.2 on 2023-07-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_mastercartpayment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pttbankpayment',
            name='address',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='pttbankpayment',
            name='not_if_any',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='pttbankpayment',
            name='phone',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
