# Generated by Django 4.2 on 2023-07-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_pttbankpayment_address_pttbankpayment_not_if_any_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='None', max_length=50)),
                ('phone', models.CharField(default='None', max_length=50)),
                ('not_if_any', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='paypalpayment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='paypalpayment',
            name='not_if_any',
        ),
        migrations.RemoveField(
            model_name='paypalpayment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='pttbankpayment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pttbankpayment',
            name='not_if_any',
        ),
        migrations.RemoveField(
            model_name='pttbankpayment',
            name='phone',
        ),
        migrations.AddField(
            model_name='mastercartpayment',
            name='page_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.pageaddress'),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='page_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.pageaddress'),
        ),
        migrations.AddField(
            model_name='pttbankpayment',
            name='page_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.pageaddress'),
        ),
    ]
