# Generated by Django 4.2 on 2023-07-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0016_delete_fooddelivery'),
        ('payment', '0009_pageaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaddress',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodmenu.order'),
        ),
    ]
