# Generated by Django 4.2 on 2023-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namerestaurant', models.CharField(blank=True, max_length=66, null=True)),
            ],
        ),
    ]
