# Generated by Django 4.2 on 2023-05-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0005_alter_bookatable_chooseaddresstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='ChooseAddressTable',
            field=models.IntegerField(default=1, max_length=2, null=True),
        ),
    ]
