# Generated by Django 4.2 on 2023-05-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0006_alter_bookatable_chooseaddresstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Image', models.ImageField(upload_to='photos/RestaurantMenu/%y/%m/%d')),
                ('Category', models.CharField(max_length=40)),
                ('Assess', models.ImageField(upload_to='photos/RestaurantMenu/Assess/%y/%m/%d')),
            ],
        ),
    ]
