# Generated by Django 4.2 on 2023-05-05 21:18

from django.db import migrations, models
import foodmenu.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0009_alter_restaurantmenu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=50)),
                ('NotesIfAny', models.TextField(max_length=100)),
                ('Address', foodmenu.models.CharOrURLField(max_length=255)),
            ],
        ),
    ]
