# Generated by Django 4.2 on 2023-05-14 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0010_fooddelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
