# Generated by Django 4.2 on 2023-05-19 23:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodmenu', '0011_alter_restaurantmenu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('is_finished', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookatable',
            name='ChooseAddressTable',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bookatable',
            name='ChooseTableSize',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Cost')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmenu.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmenu.restaurantmenu')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='detils',
            field=models.ManyToManyField(to='foodmenu.restaurantmenu'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
