# Generated by Django 4.2 on 2023-06-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0013_restaurantmenu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50)),
                ('time', models.IntegerField(default=30)),
                ('deliver_cost', models.IntegerField(default=0.75)),
            ],
        ),
    ]
