# Generated by Django 4.2 on 2023-07-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0014_static_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Static_Address',
        ),
    ]
