# Generated by Django 4.2 on 2023-07-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0015_delete_static_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodDelivery',
        ),
    ]
