# Generated by Django 4.2 on 2023-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='productfavorites',
            field=models.ManyToManyField(blank=True, null=True, to='foodmenu.food'),
        ),
    ]
