# Generated by Django 4.2 on 2023-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0012_order_alter_bookatable_chooseaddresstable_and_more'),
        ('accounts', '0002_remove_profile_country_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='productfavorites',
            field=models.ManyToManyField(to='foodmenu.restaurantmenu'),
        ),
    ]
