# Generated by Django 4.2 on 2023-07-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_static_address_remove_profile_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='sta_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.static_address', verbose_name='Static Address'),
        ),
    ]
