# Generated by Django 4.2 on 2023-05-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setteings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(),
        ),
    ]
