# Generated by Django 4.2 on 2023-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setteings', '0002_description_title_alter_description_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
