# Generated by Django 4.2 on 2023-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setteings', '0003_description_active_alter_description_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='photos/ImageOurTeam/%y/%m/%d')),
            ],
        ),
    ]
